/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef XGAME_API
#define XGAME_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern XGAME_API FName XGAME_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class XGAME_API AAimedAttachment : public AActor
{
public:
    FVector BaseOffset;
    FVector AimedOffset;
    FLOAT DownwardBias;
    DECLARE_CLASS(AAimedAttachment,AActor,0,XGame)
    #include "AAimedAttachment.h"
};


class XGAME_API USpeciesType : public UObject
{
public:
    FStringNoInit MaleVoice;
    FStringNoInit FemaleVoice;
    FStringNoInit GibGroup;
    FStringNoInit MaleRagSkelName;
    FStringNoInit FemaleRagSkelName;
    FStringNoInit FemaleSkeleton;
    FStringNoInit MaleSkeleton;
    FStringNoInit MaleSoundGroup;
    FStringNoInit FemaleSoundGroup;
    FStringNoInit PawnClassName;
    FStringNoInit SpeciesName;
    INT RaceNum;
    FLOAT AirControl;
    FLOAT GroundSpeed;
    FLOAT WaterSpeed;
    FLOAT JumpZ;
    FLOAT ReceivedDamageScaling;
    FLOAT DamageScaling;
    FLOAT AccelRate;
    FLOAT WalkingPct;
    FLOAT CrouchedPct;
    FLOAT DodgeSpeedFactor;
    FLOAT DodgeSpeedZ;
    DECLARE_CLASS(USpeciesType,UObject,0,XGame)
    NO_DEFAULT_CONSTRUCTOR(USpeciesType)
};

struct XGAME_API FMutatorRecord
{
    FStringNoInit ClassName;
    class UClass* mutClass;
    FStringNoInit IconMaterialName;
    FStringNoInit ConfigMenuClassName;
    FStringNoInit GroupName;
    FStringNoInit FriendlyName;
    FStringNoInit Description;
    BYTE bActivated;
};

struct XGAME_API FPlayerRecord
{
    FStringNoInit DefaultName;
    class UClass* Species;
    FStringNoInit MeshName;
    FStringNoInit BodySkinName;
    FStringNoInit FaceSkinName;
    class UMaterial* Portrait;
    FStringNoInit TextName;
    FStringNoInit VoiceClassName;
    FStringNoInit Sex;
    FStringNoInit Accuracy;
    FStringNoInit Aggressiveness;
    FStringNoInit StrafingAbility;
    FStringNoInit CombatStyle;
    FStringNoInit Tactics;
    FStringNoInit bJumpy;
    FStringNoInit FavoriteWeapon;
    FStringNoInit Menu;
    INT RecordIndex;
};


class XGAME_API UxUtil : public UObject
{
public:
    class UCachePlayers* CachedPlayerList;
    class UCacheMutators* CachedMutatorList;
    FStringNoInit NoPreference;
    FStringNoInit FavoriteWeapon;
    FStringNoInit AgilityString;
    FStringNoInit TacticsString;
    FStringNoInit AccuracyString;
    FStringNoInit AggressivenessString;
    DECLARE_FUNCTION(execGetMutatorList);
    DECLARE_FUNCTION(execFindPlayerRecord);
    DECLARE_FUNCTION(execGetPlayerRecord);
    DECLARE_FUNCTION(execGetPlayerList);
    DECLARE_CLASS(UxUtil,UObject,0,XGame)
    #include "UxUtil.h"
};


class XGAME_API UCacheMutators : public UxUtil
{
public:
    TArrayNoInit<FMutatorRecord> Records;
    DECLARE_CLASS(UCacheMutators,UxUtil,0,XGame)
    NO_DEFAULT_CONSTRUCTOR(UCacheMutators)
};


class XGAME_API UCachePlayers : public UxUtil
{
public:
    TArrayNoInit<FPlayerRecord> Records;
    DECLARE_CLASS(UCachePlayers,UxUtil,0,XGame)
    NO_DEFAULT_CONSTRUCTOR(UCachePlayers)
};


class XGAME_API UDecoText : public UObject
{
public:
    FStringNoInit TextName;
    TArrayNoInit<FString> Rows;
    DECLARE_CLASS(UDecoText,UObject,0,XGame)
    NO_DEFAULT_CONSTRUCTOR(UDecoText)
};

#endif

AUTOGENERATE_FUNCTION(UxUtil,573,execGetMutatorList);
AUTOGENERATE_FUNCTION(UxUtil,564,execFindPlayerRecord);
AUTOGENERATE_FUNCTION(UxUtil,563,execGetPlayerRecord);
AUTOGENERATE_FUNCTION(UxUtil,562,execGetPlayerList);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#if __STATIC_LINK
#ifndef XGAME_NATIVE_DEFS
#define XGAME_NATIVE_DEFS

DECLARE_NATIVE_TYPE(XGame,USpeciesType);
DECLARE_NATIVE_TYPE(XGame,AAimedAttachment);
DECLARE_NATIVE_TYPE(XGame,UxUtil);
DECLARE_NATIVE_TYPE(XGame,UDecoText);
DECLARE_NATIVE_TYPE(XGame,UCacheMutators);
DECLARE_NATIVE_TYPE(XGame,UCachePlayers);

#define AUTO_INITIALIZE_REGISTRANTS_XGAME \
	USpeciesType::StaticClass(); \
	AAimedAttachment::StaticClass(); \
	UxUtil::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindXGameUxUtilNative; \
	UDecoText::StaticClass(); \
	UCacheMutators::StaticClass(); \
	UCachePlayers::StaticClass(); \

#endif // XGame_NATIVE_DEFS

#ifdef NATIVES_ONLY
NATIVE_INFO(UxUtil) GXGameUxUtilNatives[] = 
{ 
	MAP_NATIVE(UxUtil,execGetMutatorList)
	MAP_NATIVE(UxUtil,execFindPlayerRecord)
	MAP_NATIVE(UxUtil,execGetPlayerRecord)
	MAP_NATIVE(UxUtil,execGetPlayerList)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(XGame,UxUtil);

#endif // NATIVES_ONLY
#endif // __STATIC_LINK
