[LevelInfo0]
Title="Tricky"

[LevelSummary]
Title="Cascades"
Description="AUJOURD'HUI SAMEDI, POUR UN JOUR SEULEMENT, DANS LA MONSTER VALLEY, VENEZ VOIR LE SPECTACLE DES TOURNOIS D'ATTAQUE !!! DEUX EQUIPES ET 65 TONNES D'ACTION ET DE DESTRUCTION MASSIVE !!! NE RATEZ PAS LES CERCEAUX ENFLAMMES, LES SAUTS MONSTRUEUX, LA RAMPE SANGLANTE, ET LES 150 METRES DE LA TOUR DE LA MORT !!! SOYEZ LA !!!"

[Volume12]
LocationName="Tour"

[ZoneInfo1]
LocationName="Extérieur"

